### ISSUE TITLE
Personal Dumbness

### ISSUE THREAD

**Issue by thepapanoob** [gamaral/marshmallow_h#1]
Hey gamaral
i really like this project!
But how am i supposed to edit the demo levels im only a Hobby Dev.
so please don't blame on me.
Greetz Kru

**Comment by gamaral** [comment]
I take it you mean for the platformer demo, the engine supports Tiled's TMX format (http://www.mapeditor.org/).

You will need to adjust the paths for the tile sheet by hand (or play around with the folders) since the engine expects relative paths (as in relative to the current working directory during execution) and Tiled relative paths are relative to the TMX file itself.

I can write a little script for you so it does it automatically, but you will have to wait a few hours (I'm headed to bed ;))

**Comment by gamaral** [comment]
Ok I fixed the relative path issue, it should now be as simple as opening the TMX file in the assets folder and editing away. I'll add more levels and maybe a few enemies so you can get an idea it all works. :)

**Comment by thepapanoob** [comment]
Wow Thats awesome :)
